
######################################
# C sources
C_SOURCES +=  \
$(MB_PARENT_DIR)/functions/mbfunccoils.c	\
$(MB_PARENT_DIR)/functions/mbfuncdiag.c	\
$(MB_PARENT_DIR)/functions/mbfuncdisc.c	\
$(MB_PARENT_DIR)/functions/mbfuncholding.c	\
$(MB_PARENT_DIR)/functions/mbfuncinput.c	\
$(MB_PARENT_DIR)/functions/mbfuncother.c	\
$(MB_PARENT_DIR)/functions/mbutils.c	\
$(MB_PARENT_DIR)/tcp/mbtcp.c	\
$(MB_PARENT_DIR)/port/portevent.c	\
$(MB_PARENT_DIR)/mb.c

# C includes
C_INCLUDES +=  \
-I$(MB_PARENT_DIR)/ascii	\
-I$(MB_PARENT_DIR)/include	\
-I$(MB_PARENT_DIR)/port	\
-I$(MB_PARENT_DIR)/rtu	\
-I$(MB_PARENT_DIR)/tcp