
######################################
# C sources
C_SOURCES +=  \
$(RTOS_PARENT_DIR)/portable/MemMang/heap_4.c	\
$(RTOS_PARENT_DIR)/portable/RVDS/ARM_CM7/r0p1/port.c	\
$(RTOS_PARENT_DIR)/croutine.c	\
$(RTOS_PARENT_DIR)/event_groups.c	\
$(RTOS_PARENT_DIR)/list.c	\
$(RTOS_PARENT_DIR)/queue.c	\
$(RTOS_PARENT_DIR)/tasks.c	\
$(RTOS_PARENT_DIR)/rtos_timers.c

# C includes
C_INCLUDES +=  \
-I$(RTOS_PARENT_DIR)/include	\
-I$(RTOS_PARENT_DIR)/portable/RVDS/ARM_CM7/r0p1

