# C sources
C_SOURCES +=  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/api/api_lib.c	\
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/api/api_msg.c	\
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/api/err.c	\
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/api/netbuf.c	\
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/api/netdb.c	\
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/api/netifapi.c	\
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/api/sockets.c	\
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/api/tcpip.c	\
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/def.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/dhcp.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/dns.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/init.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/lwip_sys.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/mem.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/memp.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/netif.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/pbuf.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/raw.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/stats.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/tcp_in.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/tcp_out.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/tcp.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/timers.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/udp.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/ipv4/autoip.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/ipv4/icmp.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/ipv4/igmp.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/ipv4/inet_chksum.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/ipv4/inet.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/ipv4/ip_addr.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/ipv4/ip_frag.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/core/ipv4/ip.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/netif/etharp.c  \
$(LWIP_PARENT_DIR)/lwip-1.4.1/src/netif/ethernetif.c	\
$(LWIP_PARENT_DIR)/arch/sys_arch.c  \


# C includes
C_INCLUDES +=  \
-I$(LWIP_PARENT_DIR)/lwip-1.4.1/src/include/ipv4	\
-I$(LWIP_PARENT_DIR)/lwip-1.4.1/src/include/netif	\
-I$(LWIP_PARENT_DIR)/lwip-1.4.1/src/include	\
-I$(LWIP_PARENT_DIR)